version: '3.8'

services:

  mysql:
    image: mysql:8

    container_name: mysql-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BibliotecaJuegos

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .

    container_name: springboot-app

    restart: always

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/BibliotecaJuegos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      - mysql

  sonarqube:
    image: sonarqube:lts-community

    container_name: sonarqube

    restart: always

    ports:
      - "9000:9000"

volumes:
  mysql-data: