spring.application.name=juegos
spring.datasource.url=jdbc:mysql://localhost:3306/bibliotecajuegos
spring.datasource.username=root
spring.datasource.password=

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Exponer los endpoints de monitoreo de Actuator
management.endpoints.web.exposure.include=health,info,prometheus

# Mostrar detalles completos del estado de salud de la app y base de datos
management.endpoint.health.show-details=always

# Habilitar el formato específico de métricas para Prometheus
management.endpoint.prometheus.enabled=true
