spring.application.name=juegos
spring.datasource.url=jdbc:mysql://localhost:3306/BibliotecaJuegos
spring.datasource.username=root
spring.datasource.password=

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
