name: Despliegue Automático con Docker en AWS

on:
  push:
    branches: [ main ] # Se activa cada vez que haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Conectarse a AWS y actualizar Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}         # La IP de tu AWS (guardada en GitHub)
        username: ${{ secrets.EC2_USERNAME }}      # El usuario de tu AWS (suele ser ubuntu)
        key: ${{ secrets.SSH_KEY }}       # Tu llave .pem (guardada en GitHub)
        script: |
          cd /home/ec2-user/Gitflow-Anthony-Sebastian2
          git pull origin main
          # Borramos imágenes antiguas para liberar espacio y evitar conflictos
          sudo docker system prune -f
          # Construimos
          sudo docker build -t mi-proyecto-profe .
          # Detenemos y borramos contenedor
          sudo docker stop contenedor-profe || true
          sudo docker rm contenedor-profe || true
          # Ejecutamos
          sudo docker run -d -p 80:3000 --name contenedor-profe mi-proyecto-profe