name: Despliegue Automático con Docker en AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Conectarse a AWS y actualizar Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}  # <-- Cambiamos esto para que use tu secreto de ayer
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ec2-user/Gitflow-Anthony-Sebastian2
          git pull origin main
          sudo docker build -t mi-proyecto-profe .
          sudo docker stop contenedor-profe || true
          sudo docker rm contenedor-profe || true
          sudo docker run -d -p 80:3000 --name contenedor-profe mi-proyecto-profe